name: giphy_get
description: ''
version: 3.1.1


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter       

  extended_image: ^6.2.1
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.7
  pedantic: ^1.11.0
  matcher: ^0.12.10 

flutter:
  # assets:
    # - assets/img/
